jazzy \
  --clean \
  --author Benjamin Encz \
  --author_url https://github.com/ReSwift/ReSwift \
  --github_url https://github.com/ReSwift/ReSwift \
  --github-file-prefix https://github.com/ReSwift/ReSwift/tree/master \
  --module-version 0.0.1 \
  --xcodebuild-arguments -scheme,ReSwift-iOS \
  --module ReSwift \
  --root-url https://github.com/ReSwift/ReSwift \
  --output docs/swift_output \
  --template-directory docs/templates \
  --exclude ReSwift/CoreTypes/MainStore.swift
