name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  swiftpm:
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Select Xcode
        uses: devbotsxyz/xcode-select@v1.1.0
        with:
          version: "14.3"

      - name: SwiftPM Test
        run: swift test

  pod-lint:
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Select Xcode
        uses: devbotsxyz/xcode-select@v1.1.0
        with:
          version: "14.3"

      - name: Pod Lint
        run: pod lib lint --verbose --allow-warnings

  test:
    timeout-minutes: 10

    env:
      LC_CTYPE: en_US.UTF-8
      LANG: en_US.UTF-8
      FRAMEWORK_NAME: "ReSwift"

    strategy:
      matrix:
        include:

        # Latest MacOS Build, with Codecov
        - scheme: macOS
          os: macos-13
          xcode: "14.3"
          sdk: "macosx13.3"
          destination: "platform=macOS"
          swift_version: "5.8"
          action: test
          update_codecov: true

        # Latest iOS Build
        - scheme: iOS
          os: macos-13
          xcode: "14.3"
          sdk: "iphonesimulator"
          destination: "OS=16.4,name=iPhone 14 Pro"
          swift_version: "5.8"
          action: test
          update_codecov: false

        # Latest watchOS Build
        - scheme: watchOS
          os: macos-13
          xcode: "14.3"
          sdk: "watchsimulator"
          destination: "OS=9.4,name=Apple Watch Series 8 - 45mm"
          swift_version: "5.8"
          action: build
          update_codecov: false

        # Latest tvOS Build
        - scheme: tvOS
          os: macos-13
          xcode: "14.3"
          sdk: "appletvsimulator"
          destination: "OS=15.2,name=Apple TV 4K"
          swift_version: "5.8"
          action: test

        # Swift 5.2 for backwards compatibility
        # Available runners: https://github.com/actions/runner-images/blob/main/images/macos/macos-11-Readme.md
        - scheme: macOS
          os: macos-11
          xcode: "11.7"
          sdk: "macosx10.15"
          destination: "platform=macOS"
          swift_version: "5.2"
          action: test
          update_codecov: true

    runs-on: "${{ matrix.os }}"
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Select Xcode
        uses: devbotsxyz/xcode-select@v1.1.0
        with:
          version: "${{ matrix.xcode }}"

      - name: Build and Test
        run: |
          xcodebuild ${{ matrix.action }} \
            -project "${{ env.FRAMEWORK_NAME }}.xcodeproj" \
            -scheme "${{ env.FRAMEWORK_NAME }}-${{ matrix.scheme }}" \
            -sdk "${{ matrix.sdk }}" \
            -destination "${{ matrix.destination }}" \
            -configuration Debug \
            ONLY_ACTIVE_ARCH=YES \
            GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES \
            GCC_GENERATE_TEST_COVERAGE_FILES=YES \
            SWIFT_VERSION=${{ matrix.SWIFT_VERSION }}

      - name: Convert code coverage
        if: matrix.update_codecov == true
        uses: sersoft-gmbh/xcode-coverage-action@v3
        id: xcode-cov

      - name: Codecov
        if: matrix.update_codecov == true
        uses: codecov/codecov-action@v2
        with:
          files: ${{join(fromJSON(steps.xcode-cov.outputs.files), ',')}}
          fail_ci_if_error: true
          verbose: true
